"use client";

import { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, Puzzle } from "lucide-react";
import { trackDownloadClick, trackExtensionClick } from "@/lib/gtag";
import BrandsStrip from "@/components/sections/BrandsStrip";
import HeroCloudBackground from "@/components/sections/hero/HeroCloudBackground";
import HeroOutfitCarousel from "@/components/sections/hero/HeroOutfitCarousel";

const CAROUSEL_CARDS = [
  { label: "Casual", rotate: -8, yOffset: 56, img: "/outfit-casual.jpg", alt: "Casual outfit idea generated by Slidez AI stylist app", prompt: "Casual everyday look, effortless and comfortable" },
  { label: "Work", rotate: -4, yOffset: 28, img: "/outfit-work.jpg", alt: "AI fashion stylist work outfit suggestion with virtual try-on", prompt: "Sharp office outfit, polished and professional" },
  { label: "Night Out", rotate: 0, yOffset: 0, img: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&q=85&fit=crop&crop=top", alt: "Night out outfit generated by AI stylist outfit generator Slidez", prompt: "Night out look, glamorous and confident" },
  { label: "Weekend", rotate: 4, yOffset: 28, img: "/outfit-weekend.jpg", alt: "Weekend look from Slidez AI virtual try-on clothing preview", prompt: "Relaxed weekend brunch, stylish but laid-back" },
  { label: "Vacation", rotate: 8, yOffset: 56, img: "/outfit-vacation.jpg", alt: "Vacation outfit idea previewed with Slidez AI virtual try-on", prompt: "Vacation outfit, breezy and summery" },
];

export default function Hero() {
  const [reduceMotion, setReduceMotion] = useState(false);
  const [hoveredIdx, setHoveredIdx] = useState<number | null>(null);
  const carouselRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    setReduceMotion(window.matchMedia("(prefers-reduced-motion: reduce)").matches);
  }, []);

  useEffect(() => {
    if (carouselRef.current && window.innerWidth < 768) {
      const el = carouselRef.current;
      const centerCard = el.children[2] as HTMLElement;
      if (centerCard) {
        const scrollPos = centerCard.offsetLeft - el.clientWidth / 2 + centerCard.clientWidth / 2;
        el.scrollTo({ left: scrollPos, behavior: "smooth" });
      }
    }
  }, []);

  const handleCardClick = () => {
    trackDownloadClick();
    window.open("https://linkly.link/2FWYm", "_blank");
  };

  return (
    <section
      data-nav-theme="light-bg"
      aria-label="Slidez AI Stylist hero"
      className="relative min-h-screen overflow-hidden bg-[#ffffff] px-6 pb-0 pt-32 font-sans sm:pt-36 lg:px-[52px] lg:pb-[68px] lg:pt-32"
    >
      <HeroCloudBackground />

      <div className="relative z-[1] mx-auto w-full max-w-[1280px]">
        {/* Two-column grid */}
        <div className="grid grid-cols-1 items-center gap-10 md:grid-cols-2 md:gap-11">
          {/* Left column: Typography & CTAs */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.65, ease: [0.22, 1, 0.36, 1] }}
            className="flex flex-col items-center text-center md:items-start md:text-left"
          >
            {/* Headline */}
            <h1
              className="mt-6 text-[3.5rem] font-semibold leading-[0.9] tracking-[-3px] text-[#1a1a1e] sm:text-[4rem] md:mt-10 md:text-[4.75rem] md:tracking-[-5px] lg:text-[5.8rem]"
              suppressHydrationWarning
            >
              Dress
              <br />
              for any
              <br />
              <span
                className="font-sacramento text-[4rem] font-normal tracking-normal sm:text-[4.5rem] md:text-[5.75rem] lg:text-[6.5rem]"
                style={{ fontFamily: "var(--font-sacramento), cursive" }}
              >
                moment
              </span>
            </h1>

            <p className="mx-auto mt-6 max-w-[410px] text-sm leading-[1.55] tracking-[-0.2px] text-[#737380] sm:text-base md:mx-0 md:mt-8 md:text-lg">
              Describe the occasion. Slidez styles a head-to-toe look and shows it on you using products from brands you already shop.
            </p>

            {/* CTAs */}
            <div className="mt-8 flex flex-col items-center gap-3 sm:flex-row sm:justify-center md:items-start md:justify-start">
              <a
                href="https://linkly.link/2FWYm"
                onClick={trackDownloadClick}
                className="flex items-center gap-2 rounded-full bg-[#1a1a1e] px-7 py-3.5 text-sm font-semibold text-white shadow-[0_4px_20px_rgba(0,0,0,0.15)] transition-all duration-200 hover:-translate-y-px hover:scale-[1.03] active:scale-[0.97]"
              >
                <svg className="h-5 w-5" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path d="M18.71 19.5c-.83 1.24-1.71 2.45-3.05 2.47-1.34.03-1.77-.79-3.29-.79-1.53 0-2 .77-3.27.82-1.31.05-2.3-1.32-3.14-2.53C4.25 17 2.94 12.45 4.7 9.39c.87-1.52 2.43-2.48 4.12-2.51 1.28-.02 2.5.87 3.29.87.78 0 2.26-1.07 3.8-.91.65.03 2.47.26 3.64 1.98-.09.06-2.17 1.28-2.15 3.81.03 3.02 2.65 4.03 2.68 4.04-.03.07-.42 1.44-1.38 2.83M13 3.5c.73-.83 1.94-1.46 2.94-1.5.13 1.17-.34 2.35-1.04 3.19-.69.85-1.83 1.51-2.95 1.42-.15-1.15.41-2.35 1.05-3.11z" />
                </svg>
                Download App
              </a>
              <a
                href="https://chromewebstore.google.com/detail/kdcmgmfnnheiegkakcbkdolehlgdlaak?utm_source=item-share-cb"
                onClick={trackExtensionClick}
                className="flex items-center gap-2 rounded-full border border-black/15 px-7 py-3.5 text-sm font-medium text-[#555] transition-all duration-200 hover:-translate-y-px hover:border-black/30 hover:text-[#1a1a1e] active:scale-[0.97]"
              >
                <Puzzle className="h-4 w-4" />
                Add to Chrome
              </a>
            </div>

            <p className="mt-4 text-center text-xs text-[#9a9aa5] md:text-left">
              Free on Google Play and the App Store, plus a Chrome extension for the US and worldwide.
            </p>
          </motion.div>

          {/* Right column — mixed-and-matched outfit carousel */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.65, delay: 0.15, ease: [0.22, 1, 0.36, 1] }}
            className="relative z-[2] w-full min-w-0 flex items-center justify-center"
          >
            <HeroOutfitCarousel />
          </motion.div>
        </div>

        {/* Brands strip — below hero content, centered */}
        <div className="mt-12 w-full text-center md:mt-14">
          <BrandsStrip theme="light" variant="compact" subtitle="" />
        </div>
      </div>

      {/* Outfit card carousel */}
      <div className="relative z-10 mt-12 w-full pb-8 lg:mt-16">
        <p className="mb-5 text-center text-xs font-medium uppercase tracking-widest text-[#888]">
          Explore curated styles from Slidez
        </p>
        <div className="pointer-events-none absolute inset-y-0 left-0 z-10 w-3 sm:w-12 md:w-20 bg-gradient-to-r from-[#ffffff] to-transparent" />
        <div className="pointer-events-none absolute inset-y-0 right-0 z-10 w-3 sm:w-12 md:w-20 bg-gradient-to-l from-[#ffffff] to-transparent" />

        <div
          ref={carouselRef}
          className="flex items-end justify-center gap-1 overflow-x-auto pb-16 pt-4 px-1 sm:gap-2.5 sm:px-6 md:gap-3 md:px-4 no-scrollbar snap-x snap-mandatory touch-pan-x"
        >
          {CAROUSEL_CARDS.map((card, i) => {
            const isCenter = i === 2;
            const isAdjacent = Math.abs(i - 2) === 1;
            const isHovered = !reduceMotion && hoveredIdx === i;
            const otherHovered = hoveredIdx !== null && !isHovered;
            const targetY = isHovered ? card.yOffset - 16 : card.yOffset;

            return (
              <motion.div
                key={card.label}
                role="button"
                tabIndex={0}
                aria-label={`Style: ${card.prompt}`}
                initial={{ opacity: 0, y: 80 }}
                animate={{
                  opacity: 1,
                  y: targetY,
                  scale: isHovered ? 1.15 : otherHovered ? 0.94 : 1,
                }}
                transition={{
                  opacity: { duration: 0.9, delay: 0.15 + i * 0.1, ease: [0.22, 1, 0.36, 1] },
                  y: hoveredIdx !== null
                    ? { duration: 0.35, ease: [0.22, 1, 0.36, 1] }
                    : { duration: 0.9, delay: 0.15 + i * 0.1, ease: [0.22, 1, 0.36, 1] },
                  scale: { duration: 0.35, ease: [0.22, 1, 0.36, 1] },
                }}
                onHoverStart={() => !reduceMotion && setHoveredIdx(i)}
                onHoverEnd={() => setHoveredIdx(null)}
                onClick={handleCardClick}
                onKeyDown={(e) => (e.key === "Enter" || e.key === " ") && handleCardClick()}
                style={{
                  rotate: card.rotate,
                  zIndex: isHovered ? 20 : 1,
                  cursor: "pointer",
                  boxShadow: isHovered
                    ? "0 32px 64px rgba(0,0,0,0.22), 0 0 0 1px rgba(0,0,0,0.12)"
                    : isCenter
                      ? "0 24px 48px rgba(0,0,0,0.18), 0 0 0 1px rgba(0,0,0,0.08)"
                      : "0 16px 36px rgba(0,0,0,0.14)",
                }}
                className={`relative shrink-0 snap-center overflow-hidden transition-all duration-300 ${isCenter
                  ? "h-[270px] w-[116px] rounded-[22px] border-2 border-black/10 sm:h-[360px] sm:w-48 sm:rounded-[32px] md:h-[460px] md:w-56 md:rounded-[40px]"
                  : isAdjacent
                    ? "h-[230px] w-[96px] rounded-[18px] border border-black/[0.08] sm:h-[300px] sm:w-38 sm:rounded-[28px] md:h-[380px] md:w-44 md:rounded-[36px]"
                    : "h-[195px] w-[80px] rounded-[16px] border border-black/[0.06] sm:h-[250px] sm:w-30 sm:rounded-[24px] md:h-[310px] md:w-36 md:rounded-[32px]"
                  }`}
              >
                <img
                  src={card.img}
                  alt={card.alt}
                  loading={isCenter ? "eager" : "lazy"}
                  fetchPriority={isCenter ? "high" : "low"}
                  decoding={isCenter ? "sync" : "async"}
                  className="absolute inset-0 h-full w-full object-cover"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/10 to-black/25" />

                <AnimatePresence>
                  {isHovered && (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      exit={{ opacity: 0 }}
                      transition={{ duration: 0.18 }}
                      className="absolute inset-0 z-10 flex flex-col items-center justify-end px-3 pb-14"
                      style={{ background: "linear-gradient(to top, rgba(0,0,0,0.82) 40%, transparent 100%)" }}
                    >
                      <p className={`text-center font-medium leading-snug text-white/90 ${isCenter ? "text-[11px]" : "text-[9px]"}`}>
                        &ldquo;{card.prompt}&rdquo;
                      </p>
                      <div className="mt-2 flex items-center gap-1">
                        <Sparkles className={`text-white/70 ${isCenter ? "h-3 w-3" : "h-2.5 w-2.5"}`} />
                        <span className={`font-semibold text-white/70 ${isCenter ? "text-[10px]" : "text-[9px]"}`}>Get Look</span>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>

                <div className="absolute bottom-2.5 left-0 right-0 z-10 flex justify-center sm:bottom-4">
                  <span className={`rounded-full border border-white/20 bg-black/50 px-2 py-0.5 font-medium text-white/90 backdrop-blur-md sm:px-3 sm:py-1 ${isCenter ? "text-[10px] sm:text-xs" : "text-[8px] sm:text-[10px]"}`}>
                    {card.label}
                  </span>
                </div>

                <div className={`absolute left-1/2 top-0 z-20 -translate-x-1/2 rounded-b-2xl bg-[#ffffff] ${isCenter ? "h-4 w-12 sm:h-5 sm:w-16" : "h-3 w-10 sm:h-4 sm:w-12"}`} />
              </motion.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

