"use client";

import { useState, useEffect, useRef, useCallback, lazy, Suspense } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowRight, Star, Sparkles, Send, X, Puzzle } from "lucide-react";
import { trackDownloadClick, trackExtensionClick, trackStylistDemoSubmit } from "@/lib/gtag";
import BrandsStrip from "@/components/sections/BrandsStrip";
import type { FloatingStylerOnCompletePayload } from "@/components/ui/floating-styler";
import {
  analyzeOutfitIntentCallable,
  detectPersonGenderCallable,
  ensureAnonymousUserId,
  executeMultiItemTryOnCallable,
  fetchOutfitProductsCallable,
  fetchImageBase64,
  setupPersonPhoto,
} from "@/lib/slidezCallableFunctions";

const FloatingStyler = lazy(() =>
  import("@/components/ui/floating-styler").then((m) => ({ default: m.FloatingStyler }))
);

/* ── Typewriter prompts ───────────────────────────────────────── */
const PROMPTS = [
  "Style me for a date night...",
  "Beach vacation look...",
  "Business casual, but make it edgy...",
  "Something for a job interview...",
  "Cozy Sunday brunch outfit...",
  "Black tie, keep it minimal...",
];

// Keep the original landing-page UX flow (floating picker + result cards).
// API calls will be wired into this same flow below.
const USE_REAL_STYLIST_TOOL = false;

/* ── Pre-defined outfit results ──────────────────────────────── */
const OUTFIT_SETS = [
  {
    tag: "Top Pick",
    name: "Effortless Evening",
    pieces: ["Black slip dress", "Strappy heeled mules", "Micro leather bag", "Gold hoop earrings"],
    swatches: ["#1a1a1a", "#c0c0c0", "#e8d5b7"],
  },
  {
    tag: "Alternative",
    name: "Sharp & Chic",
    pieces: ["Fitted blazer", "Silk cami", "Tailored trousers", "Pointed-toe flats"],
    swatches: ["#2d2d2d", "#f0f0f0", "#808080"],
  },
  {
    tag: "Bold Choice",
    name: "Statement Look",
    pieces: ["Wrap midi skirt", "Fitted turtleneck", "Block-heel boots", "Structured tote"],
    swatches: ["#3a3a3a", "#d4d4d4", "#a0a0a0"],
  },
];

/* ── Outfit card carousel (background) ───────────────────────── */
const CAROUSEL_CARDS = [
  { label: "Casual", rotate: -8, yOffset: 56, img: "/outfit-casual.jpg", alt: "Casual outfit idea generated by Slidez AI stylist app", prompt: "Casual everyday look, effortless and comfortable" },
  { label: "Work", rotate: -4, yOffset: 28, img: "/outfit-work.jpg", alt: "AI fashion stylist work outfit suggestion with virtual try-on", prompt: "Sharp office outfit, polished and professional" },
  { label: "Night Out", rotate: 0, yOffset: 0, img: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&q=85&fit=crop&crop=top", alt: "Night out outfit generated by AI stylist outfit generator Slidez", prompt: "Night out look, glamorous and confident" },
  { label: "Weekend", rotate: 4, yOffset: 28, img: "/outfit-weekend.jpg", alt: "Weekend look from Slidez AI virtual try-on clothing preview", prompt: "Relaxed weekend brunch, stylish but laid-back" },
  { label: "Vacation", rotate: 8, yOffset: 56, img: "/outfit-vacation.jpg", alt: "Vacation outfit idea previewed with Slidez AI virtual try-on", prompt: "Vacation outfit, breezy and summery" },
];

/* ── Typewriter hook ─────────────────────────────────────────── */
function useTypewriter(active: boolean) {
  const [displayed, setDisplayed] = useState("");
  const promptIdx = useRef(0);
  const charIdx = useRef(0);
  const deleting = useRef(false);
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const tick = useCallback(function tick() {
    const current = PROMPTS[promptIdx.current];

    if (!deleting.current) {
      // Typing
      charIdx.current += 1;
      setDisplayed(current.slice(0, charIdx.current));
      if (charIdx.current === current.length) {
        // Pause then start deleting
        deleting.current = true;
        timer.current = setTimeout(tick, 2000);
        return;
      }
      timer.current = setTimeout(tick, 60);
    } else {
      // Deleting
      charIdx.current -= 1;
      setDisplayed(current.slice(0, charIdx.current));
      if (charIdx.current === 0) {
        deleting.current = false;
        promptIdx.current = (promptIdx.current + 1) % PROMPTS.length;
        timer.current = setTimeout(tick, 400);
        return;
      }
      timer.current = setTimeout(tick, 35);
    }
  }, []);

  useEffect(() => {
    if (!active) return;
    timer.current = setTimeout(tick, 800);
    return () => {
      if (timer.current) clearTimeout(timer.current);
    };
  }, [active, tick]);

  return displayed;
}

const OVERLAY_CONTAINER_VARIANTS = {
  hidden: {},
  show: { transition: { staggerChildren: 0.32, delayChildren: 0.2 } },
};
const OVERLAY_CARD_VARIANTS = (i: number) => ({
  hidden: { x: i % 2 === 0 ? -70 : 70, opacity: 0 },
  show: { x: 0, opacity: 1, transition: { duration: 0.45, ease: [0.22, 1, 0.36, 1] as const } },
});

/* ── Main component ──────────────────────────────────────────── */
export default function Hero() {
  const [inputValue, setInputValue] = useState("");
  const [activePrompt, setActivePrompt] = useState("");
  const [results, setResults] = useState(false);
  const [loading, setLoading] = useState(false);
  const [showStyler, setShowStyler] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const tryOnRunSeqRef = useRef(0);
  const [tryOnCards, setTryOnCards] = useState<Array<{ tag: string; name: string; imageUrl: string }>>([]);
  const [tryOnError, setTryOnError] = useState<string | null>(null);
  const [tryOnLoading, setTryOnLoading] = useState(false);
  const [selectedModelSrc, setSelectedModelSrc] = useState<string | null>(null);
  const [productItems, setProductItems] = useState<Array<{ category: string; name: string; imageUrl: string | null; productLink: string | null }>>([]);
  const placeholder = useTypewriter(!inputValue && !results);

  const handleSubmit = () => {
    if (!inputValue.trim()) return;
    trackStylistDemoSubmit();
    setLoading(true);
    setActivePrompt(inputValue.trim());
    setTryOnCards([]);
    setProductItems([]);
    setTryOnError(null);
    setShowStyler(true);
  };

  const handleCardClick = (prompt: string) => {
    trackStylistDemoSubmit();
    setInputValue(prompt);
    setActivePrompt(prompt);
    setResults(false);
    setLoading(true);
    setTryOnCards([]);
    setProductItems([]);
    setTryOnError(null);
    setShowStyler(true);
  };

  const handleStylerComplete = useCallback(
    async (payload: FloatingStylerOnCompletePayload) => {
      const runSeq = ++tryOnRunSeqRef.current;
      setShowStyler(false);
      setTryOnLoading(true);

      // Immediately show the selected model image during loading
      if (payload.avatar === "upload" && payload.uploadedFile) {
        setSelectedModelSrc(URL.createObjectURL(payload.uploadedFile));
      } else {
        setSelectedModelSrc(payload.modelSrc || "/models/brunette-white-man.png");
      }

      void (async () => {
        try {
          const userId = await ensureAnonymousUserId();
          const prompt = activePrompt.trim();
          if (!prompt) throw new Error("Missing prompt. Please try again.");

          // ── 1. Resolve person image + gender ──────────────────────
          let selectedGender: "Men" | "Women" | null =
            payload.chosenGender ?? null;

          let personImageBase64: string;
          let personMimeType: string;

          if (payload.avatar === "upload") {
            if (!payload.uploadedFile) throw new Error("Please upload a photo to continue.");
            const dataUrl = await new Promise<string>((resolve, reject) => {
              const reader = new FileReader();
              reader.onload = () => resolve(String(reader.result));
              reader.onerror = () => reject(new Error("Failed to read uploaded image."));
              reader.readAsDataURL(payload.uploadedFile!);
            });
            const commaIdx = dataUrl.indexOf(",");
            personImageBase64 = commaIdx >= 0 ? dataUrl.slice(commaIdx + 1) : dataUrl;
            personMimeType = payload.uploadedFile.type || "image/jpeg";

            // Auto-detect gender from the uploaded photo
            const detected = await detectPersonGenderCallable({ imageBase64: personImageBase64, mimeType: personMimeType });
            selectedGender = detected === "male" ? "Men" : detected === "female" ? "Women" : null;
            if (!selectedGender) throw new Error("Could not detect gender from your photo. Please try a clearer photo or use a preset model.");
          } else {
            // Preset model images from the public folder
            const src = payload.modelSrc || "/models/brunette-white-man.png";
            ({ imageBase64: personImageBase64, mimeType: personMimeType } = await fetchImageBase64(src));
          }

          if (!selectedGender) throw new Error("Please select a model.");

          // ── 2. Upload person image → Firebase Storage → Firestore ──
          await setupPersonPhoto(userId, personImageBase64, personMimeType);

          // ── 3. Analyze outfit intent ───────────────────────────────
          const intent = await analyzeOutfitIntentCallable({ prompt, gender: selectedGender });

          // ── 4. Fetch matching products ─────────────────────────────
          const products = (await fetchOutfitProductsCallable({ intent, productsPerCategory: 3, userId })) as { recommendations?: unknown[] };
          const recommendations = Array.isArray(products.recommendations) ? products.recommendations : [];

          const productInfos = recommendations.flatMap((rec) => {
            const r = rec as Record<string, unknown>;
            const slotCategory = typeof r["category"] === "string" ? r["category"] : "Product";
            const products = Array.isArray(r["products"]) ? r["products"] as Record<string, unknown>[] : [];
            // Take only the first product per slot (coherence pass already picked the best)
            const p = products[0];
            if (!p) return [];
            const str = (k: string) => (typeof p[k] === "string" ? (p[k] as string) : null);
            const media = (typeof p["media"] === "object" && p["media"] !== null ? p["media"] : {}) as Record<string, unknown>;
            const imageUrl =
              (typeof media["productImage"] === "string" ? media["productImage"] : null) ??
              str("productImage") ??
              null;
            const productLink =
              str("sourceUrl") ?? str("productUrl") ??  null;
            return [{
              category: slotCategory,
              name: str("productName") ?? str("name") ?? str("title") ?? slotCategory,
              imageUrl,
              productLink,
            }];
          });
          setProductItems(productInfos);

          // ── 5. Run virtual try-on ──────────────────────────────────
          const tryOn = (await executeMultiItemTryOnCallable({ recommendations, userId })) as { itemResults?: unknown[]; finalImageUrl?: string };
          const itemResults = Array.isArray(tryOn.itemResults) ? tryOn.itemResults : [];

          const cards = itemResults
            .filter((it) => typeof (it as Record<string, unknown>)?.resultImageUrl === "string")
            .slice(0, 3)
            .map((it, i) => {
              const itObj = it as Record<string, unknown>;
              return {
                tag: i === 0 ? "Top Pick" : i === 1 ? "Alternative" : "Bold Choice",
                name: typeof itObj.category === "string" ? itObj.category.replace(/_/g, " ") : "Outfit",
                imageUrl: itObj.resultImageUrl as string,
              };
            });

          if (runSeq !== tryOnRunSeqRef.current) return;
          setTryOnCards(cards);
          if (cards.length === 0) setTryOnError("No try-on results were generated. Please try again.");
        } catch (e) {
          const message = e instanceof Error ? e.message : "Failed to generate your try-on. Please try again.";
          if (runSeq !== tryOnRunSeqRef.current) return;
          setTryOnError(message);
          setTryOnCards([]);
        } finally {
          if (runSeq === tryOnRunSeqRef.current) setTryOnLoading(false);
        }
      })();

      // Show the results section immediately while the pipeline runs in the background.
      setTimeout(() => {
        setLoading(false);
        setResults(true);
      }, 400);
    },
    [activePrompt]
  );

  const handleReset = () => {
    setInputValue("");
    setActivePrompt("");
    setResults(false);
    setLoading(false);
    setTryOnCards([]);
    setProductItems([]);
    setTryOnError(null);
    setTryOnLoading(false);
    setSelectedModelSrc(null);
    tryOnRunSeqRef.current++;
    inputRef.current?.focus();
  };

  const [hoveredIdx, setHoveredIdx] = useState<number | null>(null);

  return (
    <section aria-label="Slidez AI Stylist hero" className="relative min-h-screen flex flex-col items-center justify-center text-center px-6 pt-28 pb-0 overflow-visible bg-black">
      {/* ── Content ─────────────────────────────────────────── */}
      <motion.div
        initial={{ opacity: 0, y: 28 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.65, ease: [0.22, 1, 0.36, 1] }}
        className="relative z-10 w-full max-w-3xl mx-auto"
      >

        {/* Headline */}
        <h1 className="text-[clamp(2.6rem,8vw,5.5rem)] font-bold leading-[1.05] tracking-tight mb-6">
          <span className="text-white">The Ultimate</span>
          <br />
          <span className="text-white">AI Stylist</span>
        </h1>

        {/* Sub */}
        <p className="text-lg md:text-xl text-white/50 max-w-xl mx-auto mb-10 leading-relaxed">
          AI stylist & virtual try-on. Style yourself in seconds.
        </p>

        {!USE_REAL_STYLIST_TOOL && (
          <>
            {/* ── Animated Input Box ──────────────────────────── */}
            <div className="relative w-full max-w-xl mx-auto mb-8">
              <div
                className={`flex items-center gap-3 px-5 py-3.5 rounded-full border transition-all duration-300 hover:border-[rgba(192,192,192,0.28)] hover:bg-[rgba(255,255,255,0.05)] hover:input-glow-hover ${results
                  ? "border-[rgba(192,192,192,0.3)] bg-[rgba(192,192,192,0.05)]"
                  : "border-[rgba(192,192,192,0.15)] bg-[rgba(255,255,255,0.03)] focus-within:border-[rgba(192,192,192,0.4)] focus-within:bg-[rgba(255,255,255,0.05)] focus-within:input-glow-focus"
                  }`}
              >
                {/* Sparkles icon */}
                <Sparkles className="w-4 h-4 text-[#808080] shrink-0" />

                {/* Input */}
                <input
                  ref={inputRef}
                  type="text"
                  value={inputValue}
                  onChange={(e) => {
                    setInputValue(e.target.value);
                    if (results) setResults(false);
                  }}
                  onKeyDown={(e) => e.key === "Enter" && handleSubmit()}
                  placeholder={placeholder}
                  className="flex-1 bg-transparent text-white text-base outline-none placeholder:text-white/25 min-w-0"
                  suppressHydrationWarning
                />

                {/* Clear button */}
                <AnimatePresence>
                  {(inputValue || results) && (
                    <motion.button
                      initial={{ opacity: 0, scale: 0.8 }}
                      animate={{ opacity: 1, scale: 1 }}
                      exit={{ opacity: 0, scale: 0.8 }}
                      onClick={handleReset}
                      aria-label="Clear input"
                      className="text-white/25 hover:text-white/50 transition-colors shrink-0"
                    >
                      <X className="w-3.5 h-3.5" />
                    </motion.button>
                  )}
                </AnimatePresence>

                {/* Send button */}
                <button
                  onClick={handleSubmit}
                  disabled={!inputValue.trim() || loading}
                  aria-label="Generate outfit"
                  className="shrink-0 w-8 h-8 rounded-full gradient-silver flex items-center justify-center disabled:opacity-25 hover:opacity-85 transition-opacity"
                >
                  {loading ? (
                    <motion.div
                      animate={{ rotate: 360 }}
                      transition={{ duration: 0.8, repeat: Infinity, ease: "linear" }}
                      className="w-3.5 h-3.5 rounded-full border-2 border-black border-t-transparent"
                    />
                  ) : (
                    <Send className="w-3.5 h-3.5 text-black" />
                  )}
                </button>
              </div>

              {/* Cursor blink on typewriter */}
              {!inputValue && !results && (
                <span
                  className="absolute left-[3.25rem] top-1/2 -translate-y-1/2 w-px h-4 bg-white/30 pointer-events-none"
                  style={{ marginLeft: `${placeholder.length * 7.2}px` }}
                >
                  <motion.span
                    animate={{ opacity: [1, 0] }}
                    transition={{ duration: 0.6, repeat: Infinity, repeatType: "reverse" }}
                    className="block w-full h-full bg-white/40"
                  />
                </span>
              )}
            </div>

            {/* ── Outfit Results ───────────────────────────────── */}
            <AnimatePresence>
              {results && (
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: 10 }}
                  transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
                  className="mb-8"
                >
                  <div className="flex items-center justify-between mb-4">
                    <p className="text-xs text-white/35 uppercase tracking-widest font-medium">
                      Outfits for &ldquo;{inputValue}&rdquo;
                    </p>
                  </div>
                  {tryOnError && (
                    <p className="text-center text-[11px] text-red-400/90 mb-4">
                      {tryOnError}
                    </p>
                  )}

                  {/* Result & Loading Layout */}
                  <motion.div
                    initial={{ opacity: 0, y: 16 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.4 }}
                    className={`relative w-full mx-auto text-left mb-6 ${tryOnCards[0]?.imageUrl && productItems.length > 0 ? "flex gap-4 items-start" : "flex justify-center"}`}
                  >
                    {/* Image Card Container */}
                    <div className={`relative group cursor-pointer shrink-0 ${tryOnCards[0]?.imageUrl && productItems.length > 0 ? "w-[55%] max-w-[300px]" : "w-full max-w-[300px]"}`}>
                      <AnimatePresence mode="wait">
                        {tryOnCards[0]?.imageUrl ? (
                        <motion.div
                          key="result-image"
                          initial={{ opacity: 0 }}
                          animate={{ opacity: 1 }}
                          transition={{ duration: 0.4 }}
                        >
                          {/* Ambient glow behind card */}
                          <div className="absolute -inset-3 rounded-[2rem] bg-gradient-to-br from-white/8 via-[rgba(180,180,255,0.06)] to-transparent blur-2xl pointer-events-none transition-opacity duration-500 group-hover:opacity-150" />
                          {/* Animated shimmer border */}
                          <div className="absolute -inset-[1px] rounded-3xl bg-gradient-to-br from-white/20 via-white/5 to-white/12 pointer-events-none" />

                          {/* Glass card */}
                          <div
                            className="relative rounded-3xl overflow-hidden border border-white/10 bg-[rgba(255,255,255,0.03)]"
                            style={{ boxShadow: "0 12px 48px rgba(0,0,0,0.55), 0 0 0 0.5px rgba(255,255,255,0.07), inset 0 1px 0 rgba(255,255,255,0.08)" }}
                          >
                            {/* Top badge */}
                            <div className="absolute top-3 left-3 z-10 flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-black/50 border border-white/10"
                              style={{ backdropFilter: "blur(12px)" }}>
                              <Sparkles className="w-2.5 h-2.5 text-white/60" />
                              <span className="text-[9px] font-semibold text-white/60 tracking-[0.15em] uppercase">Top Pick</span>
                            </div>

                            {/* Image */}
                            <img
                              src={tryOnCards[0].imageUrl}
                              alt={tryOnCards[0].name}
                              className="w-full h-auto block transition-transform duration-700 group-hover:scale-[1.02]"
                              loading="lazy"
                            />

                            {/* Bottom glass overlay */}
                            <div className="absolute bottom-0 inset-x-0 px-4 pt-10 pb-4 bg-gradient-to-t from-black/75 via-black/30 to-transparent">
                              <p className="text-[9px] text-white/40 uppercase tracking-[0.14em] mb-0.5">AI Try-On</p>
                              <p className="text-[11px] font-medium text-white/80 truncate">{tryOnCards[0].name}</p>
                            </div>
                          </div>
                        </motion.div>
                      ) : (
                        <motion.div
                          key="loading-image"
                          exit={{ x: 60, opacity: 0, transition: { duration: 0.35, ease: [0.4, 0, 1, 1] } }}
                        >
                          {/* Ambient glow behind card */}
                          <div className="absolute -inset-3 rounded-[2rem] bg-gradient-to-br from-white/8 via-[rgba(180,180,255,0.06)] to-transparent blur-2xl pointer-events-none transition-opacity duration-500 opacity-50" />
                          
                          {/* Glass card loading state */}
                          <div
                            className="relative rounded-3xl border border-white/10 bg-[rgba(255,255,255,0.03)]"
                            style={{ boxShadow: "0 12px 48px rgba(0,0,0,0.55), 0 0 0 0.5px rgba(255,255,255,0.07), inset 0 1px 0 rgba(255,255,255,0.08)" }}
                          >
                            <div className="relative w-full">
                              {/* Inner: overflow-hidden for image rounded corners */}
                              <div className="absolute inset-0 rounded-3xl overflow-hidden bg-[rgba(192,192,192,0.08)]">
                                {selectedModelSrc && (
                                  <motion.img
                                    src={selectedModelSrc}
                                    alt="Your selected model"
                                    className="absolute inset-0 w-full h-full object-cover object-top"
                                    animate={{
                                      filter: [
                                        "blur(6px) brightness(0.75)",
                                        "blur(2px) brightness(1.08)",
                                        "blur(6px) brightness(0.75)",
                                      ],
                                      scale: [1.05, 1.07, 1.05],
                                    }}
                                    transition={{ duration: 2.2, repeat: Infinity, ease: "easeInOut" }}
                                  />
                                )}
                              </div>
                              
                              {/* Loading pill at top of image */}
                              <div className="absolute inset-x-0 top-0 flex justify-center pt-4 z-10">
                                <div
                                  className="flex items-center gap-2 px-3.5 py-1.5 rounded-full border border-white/10"
                                  style={{ background: "rgba(0,0,0,0.72)", backdropFilter: "blur(10px)" }}
                                >
                                  <motion.span
                                    animate={{ opacity: [0.35, 1, 0.35] }}
                                    transition={{ duration: 1.4, repeat: Infinity, ease: "easeInOut" }}
                                    className="block w-1.5 h-1.5 rounded-full bg-[#c0c0c0] shrink-0"
                                  />
                                  <span className="text-[10px] text-white/70 font-medium">Generating try-on…</span>
                                </div>
                              </div>

                              {/* Invisible spacer image to maintain aspect ratio based on original image */}
                              {selectedModelSrc ? (
                                <img
                                  src={selectedModelSrc}
                                  alt="spacer"
                                  className="w-full h-auto block opacity-0 pointer-events-none"
                                />
                              ) : (
                                <div className="w-full pb-[133%]" />
                              )}

                              {/* Overlay cards */}
                              <AnimatePresence>
                                {productItems.length > 0 && !tryOnCards[0]?.imageUrl && (
                                  <motion.div
                                    key="overlay-cards"
                                    className="absolute inset-x-2 bottom-2 z-20 flex flex-col gap-1"
                                    variants={OVERLAY_CONTAINER_VARIANTS}
                                    initial="hidden"
                                    animate="show"
                                    exit={{ opacity: 0, transition: { duration: 0.2 } }}
                                  >
                                    {productItems.map((item, i) => (
                                      <motion.div
                                        key={i}
                                        variants={OVERLAY_CARD_VARIANTS(i)}
                                        className="relative"
                                      >
                                        {item.productLink ? (
                                          <a
                                            href={item.productLink}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="flex items-center gap-2 px-2.5 py-2 rounded-xl border border-white/10 bg-[rgba(10,10,10,0.78)] hover:bg-[rgba(20,20,20,0.85)] hover:border-white/20 transition-all cursor-pointer"
                                            style={{ backdropFilter: "blur(8px)" }}
                                          >
                                            {item.imageUrl ? (
                                              <img src={item.imageUrl} alt={item.name}
                                                   className="w-8 h-8 rounded-lg object-cover shrink-0 border border-white/[0.06]" />
                                            ) : (
                                              <div className="w-8 h-8 rounded-lg bg-white/5 shrink-0 flex items-center justify-center">
                                                <span className="text-[8px] font-bold text-white/20 uppercase">{item.category.slice(0, 1)}</span>
                                              </div>
                                            )}
                                            <div className="flex-1 min-w-0">
                                              <p className="text-[10px] font-semibold text-white/80 leading-tight line-clamp-1">{item.name}</p>
                                              <p className="text-[8px] text-white/30 uppercase tracking-wide truncate">{item.category}</p>
                                            </div>
                                          </a>
                                        ) : (
                                          <div
                                            className="flex items-center gap-2 px-2.5 py-2 rounded-xl border border-white/10 bg-[rgba(10,10,10,0.78)]"
                                            style={{ backdropFilter: "blur(8px)" }}
                                          >
                                            {item.imageUrl ? (
                                              <img src={item.imageUrl} alt={item.name}
                                                   className="w-8 h-8 rounded-lg object-cover shrink-0 border border-white/[0.06]" />
                                            ) : (
                                              <div className="w-8 h-8 rounded-lg bg-white/5 shrink-0 flex items-center justify-center">
                                                <span className="text-[8px] font-bold text-white/20 uppercase">{item.category.slice(0, 1)}</span>
                                              </div>
                                            )}
                                            <div className="flex-1 min-w-0">
                                              <p className="text-[10px] font-semibold text-white/80 leading-tight line-clamp-1">{item.name}</p>
                                              <p className="text-[8px] text-white/30 uppercase tracking-wide truncate">{item.category}</p>
                                            </div>
                                          </div>
                                        )}
                                      </motion.div>
                                    ))}
                                  </motion.div>
                                )}
                              </AnimatePresence>
                            </div>
                          </div>
                        </motion.div>
                      )}
                      </AnimatePresence>
                    </div>

                    {/* Product cards stacked to the right of image */}
                    {productItems.length > 0 && tryOnCards[0]?.imageUrl && (
                      <div className="flex-1 flex flex-col gap-2 min-w-0">
                        <motion.p
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        transition={{ duration: 0.3, delay: 0.2 }}
                        className="text-[9px] text-white/25 uppercase tracking-widest mb-1 font-medium"
                      >
                        Items tried on
                      </motion.p>
                      {productItems.map((item, i) => (
                        <motion.a
                          key={i}
                          href={item.productLink ?? undefined}
                          target="_blank"
                          rel="noopener noreferrer"
                          initial={{ x: 30, opacity: 0 }}
                          animate={{ x: 0, opacity: 1 }}
                          transition={{ duration: 0.4, delay: 0.3 + i * 0.15, ease: [0.22, 1, 0.36, 1] }}
                          whileTap={{ scale: 0.97 }}
                          className={`flex items-center gap-2.5 w-full p-2.5 rounded-xl border border-[rgba(192,192,192,0.12)] bg-[rgba(255,255,255,0.03)] transition-colors text-left ${item.productLink ? 'hover:border-[rgba(192,192,192,0.28)] hover:bg-[rgba(255,255,255,0.06)] cursor-pointer' : ''}`}
                        >
                          {item.imageUrl ? (
                            <img
                              src={item.imageUrl}
                              alt={item.name}
                              className="w-11 h-11 rounded-lg object-cover shrink-0 border border-white/[0.06]"
                            />
                          ) : (
                            <div className="w-11 h-11 rounded-lg bg-[rgba(192,192,192,0.08)] shrink-0 flex items-center justify-center">
                              <span className="text-[9px] font-bold text-white/20 uppercase">{item.category.slice(0, 1)}</span>
                            </div>
                          )}
                          <div className="flex-1 min-w-0">
                            <p className="text-[11px] font-semibold text-white/80 leading-tight line-clamp-2">{item.name}</p>
                            <p className="text-[9px] text-white/30 mt-0.5 uppercase tracking-wide truncate">{item.category}</p>
                          </div>
                          <ArrowRight className="w-3 h-3 text-white/25 shrink-0" />
                        </motion.a>
                      ))}
                      </div>
                    )}
                  </motion.div>
                </motion.div>
              )}
            </AnimatePresence>
          </>
        )}


        {/* CTAs */}
        <AnimatePresence mode="wait">
          {!results && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex flex-col sm:flex-row items-center justify-center gap-3 mb-4"
            >
              <a
                href="https://linkly.link/2FWYm"
                onClick={trackDownloadClick}
                className="flex items-center gap-2 px-7 py-3.5 bg-white text-black text-sm font-semibold rounded-full
                  shadow-[0_2px_16px_rgba(255,255,255,0.28),0_1px_4px_rgba(0,0,0,0.25),inset_0_1px_0_rgba(255,255,255,0.9)]
                  hover:shadow-[0_4px_24px_rgba(255,255,255,0.45),0_2px_8px_rgba(0,0,0,0.2),inset_0_1px_0_rgba(255,255,255,0.95)]
                  hover:scale-[1.05] hover:-translate-y-px
                  active:scale-[0.97] active:shadow-[0_1px_6px_rgba(255,255,255,0.2)]
                  transition-all duration-200 cursor-pointer"
              >
                <svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path d="M18.71 19.5c-.83 1.24-1.71 2.45-3.05 2.47-1.34.03-1.77-.79-3.29-.79-1.53 0-2 .77-3.27.82-1.31.05-2.3-1.32-3.14-2.53C4.25 17 2.94 12.45 4.7 9.39c.87-1.52 2.43-2.48 4.12-2.51 1.28-.02 2.5.87 3.29.87.78 0 2.26-1.07 3.8-.91.65.03 2.47.26 3.64 1.98-.09.06-2.17 1.28-2.15 3.81.03 3.02 2.65 4.03 2.68 4.04-.03.07-.42 1.44-1.38 2.83M13 3.5c.73-.83 1.94-1.46 2.94-1.5.13 1.17-.34 2.35-1.04 3.19-.69.85-1.83 1.51-2.95 1.42-.15-1.15.41-2.35 1.05-3.11z" />
                </svg>
                Download App
              </a>
              <a
                href="https://chromewebstore.google.com/detail/kdcmgmfnnheiegkakcbkdolehlgdlaak?utm_source=item-share-cb"
                onClick={trackExtensionClick}
                className="flex items-center gap-2 px-7 py-3.5 border border-white/15 text-white/70 text-sm font-medium rounded-full hover:border-white/30 hover:text-white
                  hover:scale-[1.04] hover:-translate-y-px
                  active:scale-[0.97]
                  transition-all duration-200 cursor-pointer"
              >
                <Puzzle className="w-4 h-4" />
                Add to Chrome
              </a>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Brands strip — replaces social proof */}
        <div className="mb-6">
          <BrandsStrip theme="dark" variant="full" />
        </div>
      </motion.div>

      {!USE_REAL_STYLIST_TOOL && (
        /* ── Floating styler ──────────────────────────────────── */
        showStyler && (
          <Suspense fallback={null}>
            <FloatingStyler visible={showStyler} onComplete={handleStylerComplete} />
          </Suspense>
        )
      )}

      {/* ── Outfit card carousel ─────────────────────────────── */}
      <div className="relative z-10 w-full pb-0">
        <p className="text-xs text-white/30 text-center mb-5 tracking-widest uppercase font-medium">
          Tap any style below to try it on you
        </p>
        <div className="absolute inset-y-0 left-0 w-24 bg-gradient-to-r from-[#080808] to-transparent z-10 pointer-events-none" />
        <div className="absolute inset-y-0 right-0 w-24 bg-gradient-to-l from-[#080808] to-transparent z-10 pointer-events-none" />

        <div className="flex items-end justify-center gap-3 overflow-visible px-4">
          {CAROUSEL_CARDS.map((card, i) => {
            const isCenter = i === 2;
            const isAdjacent = Math.abs(i - 2) === 1;
            const isHovered = hoveredIdx === i;
            const otherHovered = hoveredIdx !== null && !isHovered;
            return (
              <motion.div
                key={card.label}
                role="button"
                tabIndex={0}
                aria-label={`Style me: ${card.prompt}`}
                initial={{ opacity: 0, y: 80 }}
                animate={{
                  opacity: 1,
                  y: isHovered ? card.yOffset - 16 : card.yOffset,
                  scale: isHovered ? 1.18 : otherHovered ? 0.92 : 1,
                }}
                transition={{
                  opacity: { duration: 0.9, delay: 0.15 + i * 0.1, ease: [0.22, 1, 0.36, 1] },
                  y: hoveredIdx !== null
                    ? { duration: 0.35, ease: [0.22, 1, 0.36, 1] }
                    : { duration: 0.9, delay: 0.15 + i * 0.1, ease: [0.22, 1, 0.36, 1] },
                  scale: { duration: 0.35, ease: [0.22, 1, 0.36, 1] },
                }}
                onHoverStart={() => setHoveredIdx(i)}
                onHoverEnd={() => setHoveredIdx(null)}
                onClick={() => handleCardClick(card.prompt)}
                onKeyDown={(e) => (e.key === "Enter" || e.key === " ") && handleCardClick(card.prompt)}
                style={{
                  rotate: card.rotate,
                  zIndex: isHovered ? 20 : 1,
                  cursor: "pointer",
                  boxShadow: isHovered
                    ? "0 48px 100px rgba(0,0,0,0.85), 0 0 0 1px rgba(192,192,192,0.45)"
                    : isCenter
                      ? "0 32px 80px rgba(0,0,0,0.7), 0 0 0 1px rgba(192,192,192,0.2)"
                      : "0 20px 50px rgba(0,0,0,0.5)",
                }}
                className={`relative shrink-0 overflow-hidden ${isCenter
                  ? "w-56 h-[460px] rounded-[40px] border-2 border-[rgba(192,192,192,0.25)]"
                  : isAdjacent
                    ? "w-44 h-[380px] rounded-[36px] border border-[rgba(192,192,192,0.18)]"
                    : "w-36 h-[310px] rounded-[32px] border border-[rgba(192,192,192,0.12)]"
                  }`}
              >
                <img
                  src={card.img}
                  alt={card.alt}
                  loading={isCenter ? "eager" : "lazy"}
                  fetchPriority={isCenter ? "high" : "low"}
                  decoding={isCenter ? "sync" : "async"}
                  className="absolute inset-0 w-full h-full object-cover"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/10 to-black/25" />

                {/* Hover overlay — prompt preview */}
                <AnimatePresence>
                  {isHovered && (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      exit={{ opacity: 0 }}
                      transition={{ duration: 0.18 }}
                      className="absolute inset-0 flex flex-col items-center justify-end pb-14 px-3 z-10"
                      style={{ background: "linear-gradient(to top, rgba(0,0,0,0.82) 40%, transparent 100%)" }}
                    >
                      <p className={`text-white/90 font-medium text-center leading-snug ${isCenter ? "text-[11px]" : "text-[9px]"}`}>
                        &ldquo;{card.prompt}&rdquo;
                      </p>
                      <div className="flex items-center gap-1 mt-2">
                        <Sparkles className={`text-[#c0c0c0] ${isCenter ? "w-3 h-3" : "w-2.5 h-2.5"}`} />
                        <span className={`text-[#c0c0c0] font-semibold ${isCenter ? "text-[10px]" : "text-[9px]"}`}>Style me</span>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>

                {/* Label */}
                <div className="absolute bottom-4 left-0 right-0 flex justify-center z-10">
                  <span className={`px-3 py-1 rounded-full border border-white/20 bg-black/50 backdrop-blur-md font-medium text-white/90 ${isCenter ? "text-xs" : "text-[10px]"}`}>
                    {card.label}
                  </span>
                </div>

                {/* Notch */}
                <div className={`absolute top-0 left-1/2 -translate-x-1/2 bg-[#080808] rounded-b-2xl z-20 ${isCenter ? "w-16 h-5" : "w-12 h-4"}`} />
              </motion.div>
            )
          })}
        </div>
      </div>
    </section>
  );
}
