"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, Send, X, Puzzle } from "lucide-react";
import { useAIAutocomplete, AIAutocompleteDropdown } from "@magicx-eng/ai-autocomplete-react";
import { trackDownloadClick, trackExtensionClick, trackStylistDemoSubmit } from "@/lib/gtag";
import BrandsStrip from "@/components/sections/BrandsStrip";
import HeroCloudBackground from "@/components/sections/hero/HeroCloudBackground";
import HeroModelStage from "@/components/sections/hero/HeroModelStage";
import {
  type HeroGender,
  DEFAULT_HERO_GENDER,
  DEFAULT_HERO_MODEL_ID,
  HERO_MODELS,
  getHeroModel,
  heroGenderToApi,
} from "@/components/sections/hero/hero-model-config";
import {
  analyzeOutfitIntentCallable,
  ensureAnonymousUserId,
  executeMultiItemTryOnCallable,
  fetchOutfitProductsCallable,
  fetchImageBase64,
  setupPersonPhoto,
} from "@/lib/slidezCallableFunctions";

const PROMPTS = [
  "Style me for a rooftop dinner…",
  "Beach vacation look…",
  "Business casual, but make it edgy…",
  "Something for a job interview…",
  "Cozy Sunday brunch outfit…",
  "Black tie, keep it minimal…",
];

const SUGGESTION_CHIPS = [
  { label: "Date night", prompt: "Style me for a date night..." },
  { label: "Office", prompt: "Sharp office outfit, polished and professional" },
  { label: "Weekend away", prompt: "Relaxed weekend getaway, stylish and comfortable" },
];

const CAROUSEL_CARDS = [
  { label: "Casual", rotate: -8, yOffset: 56, img: "/outfit-casual.jpg", alt: "Casual outfit idea generated by Slidez AI stylist app", prompt: "Casual everyday look, effortless and comfortable" },
  { label: "Work", rotate: -4, yOffset: 28, img: "/outfit-work.jpg", alt: "AI fashion stylist work outfit suggestion with virtual try-on", prompt: "Sharp office outfit, polished and professional" },
  { label: "Night Out", rotate: 0, yOffset: 0, img: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&q=85&fit=crop&crop=top", alt: "Night out outfit generated by AI stylist outfit generator Slidez", prompt: "Night out look, glamorous and confident" },
  { label: "Weekend", rotate: 4, yOffset: 28, img: "/outfit-weekend.jpg", alt: "Weekend look from Slidez AI virtual try-on clothing preview", prompt: "Relaxed weekend brunch, stylish but laid-back" },
  { label: "Vacation", rotate: 8, yOffset: 56, img: "/outfit-vacation.jpg", alt: "Vacation outfit idea previewed with Slidez AI virtual try-on", prompt: "Vacation outfit, breezy and summery" },
];

type TryOnPayload = {
  chosenGender: "Men" | "Women";
  modelSrc: string;
};

const TRY_ON_TIMEOUT_MS = 120_000;

async function withTimeout<T>(promise: Promise<T>, ms: number, message: string): Promise<T> {
  let timer: ReturnType<typeof setTimeout>;
  const timeout = new Promise<never>((_, reject) => {
    timer = setTimeout(() => reject(new Error(message)), ms);
  });
  try {
    return await Promise.race([promise, timeout]);
  } finally {
    clearTimeout(timer!);
  }
}

function useTypewriter(active: boolean) {
  const [displayed, setDisplayed] = useState("");
  const promptIdx = useRef(0);
  const charIdx = useRef(0);
  const deleting = useRef(false);
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const tick = useCallback(function tick() {
    const current = PROMPTS[promptIdx.current];

    if (!deleting.current) {
      charIdx.current += 1;
      setDisplayed(current.slice(0, charIdx.current));
      if (charIdx.current === current.length) {
        deleting.current = true;
        timer.current = setTimeout(tick, 2000);
        return;
      }
      timer.current = setTimeout(tick, 60);
    } else {
      charIdx.current -= 1;
      setDisplayed(current.slice(0, charIdx.current));
      if (charIdx.current === 0) {
        deleting.current = false;
        promptIdx.current = (promptIdx.current + 1) % PROMPTS.length;
        timer.current = setTimeout(tick, 400);
        return;
      }
      timer.current = setTimeout(tick, 35);
    }
  }, []);

  useEffect(() => {
    if (!active) return;
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      setDisplayed(PROMPTS[0]);
      return;
    }
    timer.current = setTimeout(tick, 800);
    return () => {
      if (timer.current) clearTimeout(timer.current);
    };
  }, [active, tick]);

  return displayed;
}

export default function Hero() {
  const [inputValue, setInputValue] = useState("");
  const [results, setResults] = useState(false);
  const [loading, setLoading] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const tryOnRunSeqRef = useRef(0);
  const [tryOnCards, setTryOnCards] = useState<Array<{ tag: string; name: string; imageUrl: string }>>([]);
  const [tryOnError, setTryOnError] = useState<string | null>(null);
  const [tryOnLoading, setTryOnLoading] = useState(false);
  const [productItems, setProductItems] = useState<Array<{ category: string; name: string; imageUrl: string | null; productLink: string | null }>>([]);

  const [gender, setGender] = useState<HeroGender>(DEFAULT_HERO_GENDER);
  const [modelId, setModelId] = useState(DEFAULT_HERO_MODEL_ID);
  const [highlightStage, setHighlightStage] = useState(false);

  const placeholder = useTypewriter(!inputValue && !results);

  const buildPayload = useCallback((): TryOnPayload => {
    const model = getHeroModel(gender, modelId);
    return {
      chosenGender: heroGenderToApi(gender),
      modelSrc: model.src,
    };
  }, [gender, modelId]);

  const runTryOnPipeline = useCallback(async (prompt: string, payload: TryOnPayload) => {
    const runSeq = ++tryOnRunSeqRef.current;
    setTryOnLoading(true);

    try {
      await withTimeout(
        (async () => {
      const userId = await ensureAnonymousUserId();
      const trimmed = prompt.trim();
      if (!trimmed) throw new Error("Missing prompt. Please try again.");

      const { imageBase64: personImageBase64, mimeType: personMimeType } = await fetchImageBase64(payload.modelSrc);

      await setupPersonPhoto(userId, personImageBase64, personMimeType);

      const intent = await analyzeOutfitIntentCallable({ prompt: trimmed, gender: payload.chosenGender });

      const products = (await fetchOutfitProductsCallable({ intent, productsPerCategory: 3, userId })) as { recommendations?: unknown[] };
      const recommendations = Array.isArray(products.recommendations) ? products.recommendations : [];

      const productInfos = recommendations.flatMap((rec) => {
        const r = rec as Record<string, unknown>;
        const slotCategory = typeof r["category"] === "string" ? r["category"] : "Product";
        const productsArr = Array.isArray(r["products"]) ? (r["products"] as Record<string, unknown>[]) : [];
        const p = productsArr[0];
        if (!p) return [];
        const str = (k: string) => (typeof p[k] === "string" ? (p[k] as string) : null);
        const media = (typeof p["media"] === "object" && p["media"] !== null ? p["media"] : {}) as Record<string, unknown>;
        const imageUrl =
          (typeof media["productImage"] === "string" ? media["productImage"] : null) ??
          str("productImage") ??
          null;
        const productLink =
          str("productLink") ?? str("link") ?? str("url") ?? str("sourceUrl") ?? str("productUrl") ?? str("shopUrl") ?? null;

        return [{
          category: slotCategory,
          name: str("productName") ?? str("name") ?? str("title") ?? slotCategory,
          imageUrl,
          productLink,
        }];
      });

      if (runSeq !== tryOnRunSeqRef.current) return;
      setProductItems(productInfos);

      const tryOn = (await executeMultiItemTryOnCallable({ recommendations, userId })) as { itemResults?: unknown[] };
      const itemResults = Array.isArray(tryOn.itemResults) ? tryOn.itemResults : [];

      const cards = itemResults
        .filter((it) => typeof (it as Record<string, unknown>)?.resultImageUrl === "string")
        .slice(0, 3)
        .map((it, i) => {
          const itObj = it as Record<string, unknown>;
          return {
            tag: i === 0 ? "Top Pick" : i === 1 ? "Alternative" : "Bold Choice",
            name: typeof itObj.category === "string" ? itObj.category.replace(/_/g, " ") : "Outfit",
            imageUrl: itObj.resultImageUrl as string,
          };
        });

      if (runSeq !== tryOnRunSeqRef.current) return;
      setTryOnCards(cards);
      if (cards.length === 0) setTryOnError("No try-on results were generated. Please try again.");
        })(),
        TRY_ON_TIMEOUT_MS,
        "Try-on timed out. Please check your connection and try again."
      );
    } catch (e) {
      const message = e instanceof Error ? e.message : "Failed to generate your try-on. Please try again.";
      if (runSeq !== tryOnRunSeqRef.current) return;
      setTryOnError(message);
      setTryOnCards([]);
    } finally {
      if (runSeq === tryOnRunSeqRef.current) {
        setTryOnLoading(false);
        setLoading(false);
      }
    }
  }, []);

  const startTryOn = useCallback(
    (prompt: string) => {
      const trimmed = prompt.trim();
      if (!trimmed) return;

      if (!modelId) {
        setHighlightStage(true);
        setTimeout(() => setHighlightStage(false), 2000);
        return;
      }

      trackStylistDemoSubmit();
      setLoading(true);
      setInputValue(trimmed);
      setTryOnCards([]);
      setProductItems([]);
      setTryOnError(null);
      setResults(true);
      setHighlightStage(false);

      void runTryOnPipeline(trimmed, buildPayload());
    },
    [buildPayload, modelId, runTryOnPipeline]
  );

  const { inputProps, dropdownProps, reset: resetAutocomplete } = useAIAutocomplete({
    apiConfig: {
      endpoint: process.env.NEXT_PUBLIC_AI_AUTOCOMPLETE_ENDPOINT,
      apiKey: process.env.NEXT_PUBLIC_AI_AUTOCOMPLETE_API_KEY,
    },
    value: inputValue,
    onChange: (v) => {
      setInputValue(v);
    },
    onSubmit: (result) => {
      const query = result.query.trim();
      if (!query) return;
      startTryOn(query);
    },
  });

  const handleSubmit = () => {
    if (!inputValue.trim() || loading) return;
    startTryOn(inputValue);
  };

  const handleChipClick = (prompt: string) => {
    setInputValue(prompt);
    startTryOn(prompt);
  };

  const handleCardClick = (prompt: string) => {
    startTryOn(prompt);
  };

  const handleGenderChange = (g: HeroGender) => {
    setGender(g);
    setModelId(HERO_MODELS[g][0].id);
    if (results || tryOnLoading) {
      setResults(false);
      setTryOnCards([]);
      setProductItems([]);
      setTryOnError(null);
      setTryOnLoading(false);
      setLoading(false);
      tryOnRunSeqRef.current++;
    }
  };

  const handleReset = () => {
    setInputValue("");
    setResults(false);
    setLoading(false);
    setTryOnCards([]);
    setProductItems([]);
    setTryOnError(null);
    setTryOnLoading(false);
    setHighlightStage(false);
    tryOnRunSeqRef.current++;
    resetAutocomplete();
    inputRef.current?.focus();
  };

  const [hoveredIdx, setHoveredIdx] = useState<number | null>(null);
  const [reduceMotion, setReduceMotion] = useState(false);

  useEffect(() => {
    setReduceMotion(window.matchMedia("(prefers-reduced-motion: reduce)").matches);
  }, []);

  return (
    <section
      data-nav-theme="light-bg"
      aria-label="Slidez AI Stylist hero"
      className="relative min-h-screen overflow-hidden bg-[#e8e9ec] px-6 pb-0 pt-28 font-sans lg:px-[52px] lg:pb-[68px] lg:pt-14"
    >
      <HeroCloudBackground />

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.65, ease: [0.22, 1, 0.36, 1] }}
        className="relative z-[1] mx-auto w-full max-w-[1280px]"
      >
        {/* Two-column grid */}
        <div className="grid grid-cols-1 items-center gap-10 lg:grid-cols-[1fr_0.82fr] lg:gap-11">
          {/* Left column */}
          <div className="text-left">
            {/* Eyebrow pill */}
            <div className="mb-8 inline-flex h-8 items-center gap-2 rounded-full border border-black/10 bg-white/[0.65] py-0 pl-3 pr-3.5 backdrop-blur-md">
              <span className="h-1.5 w-1.5 shrink-0 rounded-full bg-[#4caf50]" />
              <span className="font-mono text-[10.5px] uppercase tracking-[1.6px] text-[#888]">
                AI Stylist · Virtual Try-On
              </span>
            </div>

            {/* Headline */}
            <h1
              className="font-semibold leading-[0.9] tracking-[-5px] text-[#1a1a1e]"
              style={{ fontSize: "clamp(2.8rem, 7vw, 5.8rem)" }}
              suppressHydrationWarning
            >
              Dress
              <br />
              for any
              <br />
              <span className="font-sacramento font-normal tracking-normal" style={{ fontSize: "clamp(3.2rem, 7.5vw, 6.5rem)" }}>
                moment
              </span>
            </h1>

            <p className="mt-8 max-w-[410px] text-lg leading-[1.55] tracking-[-0.2px] text-[#737380]">
              Describe the occasion. Slidez styles a head-to-toe look and shows it on you — using products from brands you already shop.
            </p>

            {/* Input bar */}
            <div className="relative mt-8 max-w-[450px]">
              <div className="flex h-[60px] items-center gap-2 rounded-full border border-black/10 bg-white/[0.78] py-0 pl-[22px] pr-2 backdrop-blur-md">
                <svg width="17" height="17" viewBox="0 0 24 24" fill="none" className="shrink-0" aria-hidden>
                  <path d="M12 3 L13.6 9.2 L20 11 L13.6 12.8 L12 19 L10.4 12.8 L4 11 L10.4 9.2 Z" fill="#bbb" />
                </svg>

                <input
                  ref={inputRef}
                  type="text"
                  value={inputProps.value}
                  onChange={(e) => inputProps.onChange(e as unknown as React.ChangeEvent<HTMLTextAreaElement>)}
                  onKeyDown={(e) => inputProps.onKeyDown(e as unknown as React.KeyboardEvent<HTMLTextAreaElement>)}
                  onFocus={inputProps.onFocus}
                  onBlur={inputProps.onBlur}
                  role="combobox"
                  aria-expanded={inputProps["aria-expanded"]}
                  aria-activedescendant={inputProps["aria-activedescendant"]}
                  aria-autocomplete="list"
                  aria-controls={inputProps["aria-controls"]}
                  placeholder={placeholder}
                  className="min-w-0 flex-1 bg-transparent text-base tracking-[-0.2px] text-[#1a1a1e] outline-none placeholder:text-[#aaa]"
                  suppressHydrationWarning
                />

                <AnimatePresence>
                  {(inputValue || results) && (
                    <motion.button
                      initial={{ opacity: 0, scale: 0.8 }}
                      animate={{ opacity: 1, scale: 1 }}
                      exit={{ opacity: 0, scale: 0.8 }}
                      onClick={handleReset}
                      aria-label="Clear input"
                      className="shrink-0 text-[#aaa] transition-colors hover:text-[#555]"
                    >
                      <X className="h-3.5 w-3.5" />
                    </motion.button>
                  )}
                </AnimatePresence>

                <button
                  onClick={handleSubmit}
                  disabled={!inputValue.trim() || loading}
                  aria-label="Generate outfit"
                  className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full border-none bg-[#1a1a1e] transition-opacity hover:opacity-85 disabled:opacity-25"
                >
                  {loading ? (
                    <motion.div
                      animate={{ rotate: 360 }}
                      transition={{ duration: 0.8, repeat: Infinity, ease: "linear" }}
                      className="h-3.5 w-3.5 rounded-full border-2 border-white border-t-transparent"
                    />
                  ) : (
                    <Send className="h-4 w-4 text-white" />
                  )}
                </button>
              </div>

              {!inputValue && !results && !reduceMotion && (
                <span
                  className="pointer-events-none absolute left-[3.25rem] top-1/2 h-4 w-px -translate-y-1/2 bg-[#aaa]/40"
                  style={{ marginLeft: `${placeholder.length * 7.2}px` }}
                >
                  <motion.span
                    animate={{ opacity: [1, 0] }}
                    transition={{ duration: 0.6, repeat: Infinity, repeatType: "reverse" }}
                    className="block h-full w-full bg-[#aaa]/60"
                  />
                </span>
              )}

              <AIAutocompleteDropdown {...dropdownProps} className="mt-2 text-left" />
            </div>

            {/* Chips */}
            <div className="mt-3.5 flex flex-wrap gap-2">
              {SUGGESTION_CHIPS.map((chip) => (
                <button key={chip.label} type="button" onClick={() => handleChipClick(chip.prompt)} className="hero-chip">
                  {chip.label}
                </button>
              ))}
            </div>

            {tryOnError && !results && (
              <p className="mt-3 text-[11px] text-red-500/90">{tryOnError}</p>
            )}

            {/* CTAs */}
            <AnimatePresence mode="wait">
              {!results && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="mt-8 flex flex-col items-start gap-3 sm:flex-row"
                >
                  <a
                    href="https://linkly.link/2FWYm"
                    onClick={trackDownloadClick}
                    className="flex items-center gap-2 rounded-full bg-[#1a1a1e] px-7 py-3.5 text-sm font-semibold text-white shadow-[0_4px_20px_rgba(0,0,0,0.15)] transition-all duration-200 hover:-translate-y-px hover:scale-[1.03] active:scale-[0.97]"
                  >
                    <svg className="h-5 w-5" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path d="M18.71 19.5c-.83 1.24-1.71 2.45-3.05 2.47-1.34.03-1.77-.79-3.29-.79-1.53 0-2 .77-3.27.82-1.31.05-2.3-1.32-3.14-2.53C4.25 17 2.94 12.45 4.7 9.39c.87-1.52 2.43-2.48 4.12-2.51 1.28-.02 2.5.87 3.29.87.78 0 2.26-1.07 3.8-.91.65.03 2.47.26 3.64 1.98-.09.06-2.17 1.28-2.15 3.81.03 3.02 2.65 4.03 2.68 4.04-.03.07-.42 1.44-1.38 2.83M13 3.5c.73-.83 1.94-1.46 2.94-1.5.13 1.17-.34 2.35-1.04 3.19-.69.85-1.83 1.51-2.95 1.42-.15-1.15.41-2.35 1.05-3.11z" />
                    </svg>
                    Download App
                  </a>
                  <a
                    href="https://chromewebstore.google.com/detail/kdcmgmfnnheiegkakcbkdolehlgdlaak?utm_source=item-share-cb"
                    onClick={trackExtensionClick}
                    className="flex items-center gap-2 rounded-full border border-black/15 px-7 py-3.5 text-sm font-medium text-[#555] transition-all duration-200 hover:-translate-y-px hover:border-black/30 hover:text-[#1a1a1e] active:scale-[0.97]"
                  >
                    <Puzzle className="h-4 w-4" />
                    Add to Chrome
                  </a>
                </motion.div>
              )}
            </AnimatePresence>

            <div className="mt-8">
              <BrandsStrip theme="light" variant="full" />
            </div>
          </div>

          {/* Right column — model stage */}
          <div className="w-full min-w-0">
            <HeroModelStage
              gender={gender}
              modelId={modelId}
              onGenderChange={handleGenderChange}
              onModelChange={setModelId}
              highlight={highlightStage}
              tryOnLoading={tryOnLoading}
              resultImageUrl={tryOnCards[0]?.imageUrl ?? null}
              productItems={productItems}
              tryOnError={tryOnError}
            />
          </div>
        </div>
      </motion.div>

      {/* Outfit card carousel */}
      <div className="relative z-10 mt-12 w-full pb-8 lg:mt-16">
        <p className="mb-5 text-center text-xs font-medium uppercase tracking-widest text-[#888]">
          Tap any style below to try it on you
        </p>
        <div className="pointer-events-none absolute inset-y-0 left-0 z-10 w-24 bg-gradient-to-r from-[#e8e9ec] to-transparent" />
        <div className="pointer-events-none absolute inset-y-0 right-0 z-10 w-24 bg-gradient-to-l from-[#e8e9ec] to-transparent" />

        <div className="flex items-end justify-center gap-3 overflow-visible px-4">
          {CAROUSEL_CARDS.map((card, i) => {
            const isCenter = i === 2;
            const isAdjacent = Math.abs(i - 2) === 1;
            const isHovered = !reduceMotion && hoveredIdx === i;
            const otherHovered = hoveredIdx !== null && !isHovered;
            return (
              <motion.div
                key={card.label}
                role="button"
                tabIndex={0}
                aria-label={`Style me: ${card.prompt}`}
                initial={{ opacity: 0, y: 80 }}
                animate={{
                  opacity: 1,
                  y: isHovered ? card.yOffset - 16 : card.yOffset,
                  scale: isHovered ? 1.18 : otherHovered ? 0.92 : 1,
                }}
                transition={{
                  opacity: { duration: 0.9, delay: 0.15 + i * 0.1, ease: [0.22, 1, 0.36, 1] },
                  y: hoveredIdx !== null
                    ? { duration: 0.35, ease: [0.22, 1, 0.36, 1] }
                    : { duration: 0.9, delay: 0.15 + i * 0.1, ease: [0.22, 1, 0.36, 1] },
                  scale: { duration: 0.35, ease: [0.22, 1, 0.36, 1] },
                }}
                onHoverStart={() => !reduceMotion && setHoveredIdx(i)}
                onHoverEnd={() => setHoveredIdx(null)}
                onClick={() => handleCardClick(card.prompt)}
                onKeyDown={(e) => (e.key === "Enter" || e.key === " ") && handleCardClick(card.prompt)}
                style={{
                  rotate: card.rotate,
                  zIndex: isHovered ? 20 : 1,
                  cursor: "pointer",
                  boxShadow: isHovered
                    ? "0 32px 64px rgba(0,0,0,0.22), 0 0 0 1px rgba(0,0,0,0.12)"
                    : isCenter
                      ? "0 24px 48px rgba(0,0,0,0.18), 0 0 0 1px rgba(0,0,0,0.08)"
                      : "0 16px 36px rgba(0,0,0,0.14)",
                }}
                className={`relative shrink-0 overflow-hidden ${isCenter
                  ? "h-[460px] w-56 rounded-[40px] border-2 border-black/10"
                  : isAdjacent
                    ? "h-[380px] w-44 rounded-[36px] border border-black/[0.08]"
                    : "h-[310px] w-36 rounded-[32px] border border-black/[0.06]"
                  }`}
              >
                <img
                  src={card.img}
                  alt={card.alt}
                  loading={isCenter ? "eager" : "lazy"}
                  fetchPriority={isCenter ? "high" : "low"}
                  decoding={isCenter ? "sync" : "async"}
                  className="absolute inset-0 h-full w-full object-cover"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/10 to-black/25" />

                <AnimatePresence>
                  {isHovered && (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      exit={{ opacity: 0 }}
                      transition={{ duration: 0.18 }}
                      className="absolute inset-0 z-10 flex flex-col items-center justify-end px-3 pb-14"
                      style={{ background: "linear-gradient(to top, rgba(0,0,0,0.82) 40%, transparent 100%)" }}
                    >
                      <p className={`text-center font-medium leading-snug text-white/90 ${isCenter ? "text-[11px]" : "text-[9px]"}`}>
                        &ldquo;{card.prompt}&rdquo;
                      </p>
                      <div className="mt-2 flex items-center gap-1">
                        <Sparkles className={`text-white/70 ${isCenter ? "h-3 w-3" : "h-2.5 w-2.5"}`} />
                        <span className={`font-semibold text-white/70 ${isCenter ? "text-[10px]" : "text-[9px]"}`}>Style me</span>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>

                <div className="absolute bottom-4 left-0 right-0 z-10 flex justify-center">
                  <span className={`rounded-full border border-white/20 bg-black/50 px-3 py-1 font-medium text-white/90 backdrop-blur-md ${isCenter ? "text-xs" : "text-[10px]"}`}>
                    {card.label}
                  </span>
                </div>

                <div className={`absolute left-1/2 top-0 z-20 -translate-x-1/2 rounded-b-2xl bg-[#e8e9ec] ${isCenter ? "h-5 w-16" : "h-4 w-12"}`} />
              </motion.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
