import type { Metadata } from "next";
import OutfitIdeasTemplate from "@/components/templates/OutfitIdeasTemplate";
import {
  type OutfitPageConfig,
  generateOutfitPageMetadata,
  UNSPLASH_BASE as U,
} from "@/lib/outfit-pages";

/* ── Page config ──────────────────────────────────────────────── */

const config: OutfitPageConfig = {
  slug: "outfit-ideas",

  title: "AI Stylist – Get Instant Outfit Ideas | Slidez",
  description:
    "Describe your style, mood, or occasion and get instant AI outfit ideas. Slidez AI Stylist helps you find the perfect look for any moment — free to use.",
  keywords: [
    "outfit ideas",
    "AI stylist",
    "AI outfit generator",
    "what to wear",
    "fashion AI",
    "style ideas",
    "outfit inspiration",
    "Slidez AI Stylist",
    "outfit generator app",
    "get dressed AI",
  ],
  ogTitle: "AI Stylist – Instant Outfit Ideas | Slidez",
  ogDescription:
    "Describe your style or occasion and get instant AI outfit ideas with Slidez.",

  heroEyebrow: "AI Stylist",
  heroH1: "AI Stylist",
  heroSubtext: "Get instant outfit ideas based on your style, mood, or occasion.",

  styleCards: [
    {
      label: "Casual Everyday Outfit",
      desc: "Relaxed pieces that feel intentional — jeans, tees, and effortless layers for every day.",
      img: `${U}1539109136881-3be0616acf4b?w=400&q=85&fit=crop&crop=top`,
      alt: "Casual everyday outfit idea generated by Slidez AI Stylist",
    },
    {
      label: "Office / Work Outfit",
      desc: "Professional looks that feel modern and put-together without being stiff or overdone.",
      img: `${U}1490481651871-ab68de25d43d?w=400&q=85&fit=crop&crop=top`,
      alt: "Office work outfit idea from Slidez AI Stylist",
    },
    {
      label: "Date Night Outfit",
      desc: "Effortlessly romantic looks for dinner, drinks, or a late-night walk that turns heads.",
      img: `${U}1524504388940-b1c1722653e1?w=400&q=85&fit=crop&crop=top`,
      alt: "Date night outfit idea powered by Slidez AI",
    },
    {
      label: "Winter Layered Outfit",
      desc: "Cozy, considered layering that keeps you warm without sacrificing style or proportion.",
      img: `${U}1483985988355-763728e1935b?w=400&q=85&fit=crop&crop=top`,
      alt: "Winter layered outfit idea from Slidez AI Stylist",
    },
  ],

  whatGoesWith: [
    {
      category: "Tops",
      body: "The right top sets the tone for the entire outfit. Slidez AI matches your top — whether a fitted tee, silk blouse, or chunky knit — to bottoms, shoes, and accessories that balance proportion and vibe.",
    },
    {
      category: "Bottoms",
      body: "From wide-leg trousers to leather skirts, Slidez AI finds what pairs best above and below. It considers silhouette, fabric, and occasion to make sure nothing clashes.",
    },
    {
      category: "Shoes",
      body: "Shoes anchor the look. Slidez suggests footwear that matches the outfit's energy — sleek loafers for work, strappy heels for evening, clean sneakers for casual. The right shoe makes the outfit.",
    },
    {
      category: "Accessories",
      body: "Jewelry, bags, belts, and layers are chosen to elevate — not overpower. Slidez AI keeps accessories intentional, selecting pieces that feel finished without trying too hard.",
    },
  ],

  faqItems: [
    {
      q: "What is an AI stylist?",
      a: "An AI stylist is a smart fashion assistant that generates personalized outfit ideas based on your style, mood, or occasion. Slidez AI Stylist suggests complete looks — tops, bottoms, shoes, and accessories — tailored to what you describe.",
    },
    {
      q: "How does the Slidez AI stylist work?",
      a: "Describe what you need — a vibe, occasion, or specific item — and Slidez AI generates curated outfit suggestions with matching pieces and color palettes. The more specific you are, the more tailored the results.",
    },
    {
      q: "Can I generate outfit ideas for specific occasions?",
      a: "Yes. Slidez works for any occasion — casual everyday, office, date night, winter layering, parties, vacations, and more. Just tell the AI what you need and it builds the full look.",
    },
    {
      q: "Can I try the outfits on with Slidez?",
      a: "Yes. Slidez includes a virtual try-on feature so you can see exactly how any outfit looks on you before buying. Download the app on iOS or Android to access the full try-on experience.",
    },
  ],

  popularIdeas: [
    { label: "Black Jeans Outfit Ideas",       href: "/black-jeans-outfit-ideas"          },
    { label: "Summer Date Night Outfit Ideas", href: "/summer-date-night-outfit-ideas"    },
    { label: "Casual Coffee Date Outfit",      href: "/casual-coffee-date-outfit"         },
    { label: "Winter Outfit Ideas",            href: "/winter-outfit-ideas"               },
    { label: "Office Outfit Ideas for Women",  href: "/office-outfit-ideas-for-women"     },
    { label: "Office Outfit Ideas for Men",    href: "/office-outfit-ideas-for-men"       },
    { label: "Concert Outfit Ideas",           href: "/concert-outfit-ideas"              },
    { label: "Party Night Outfit Ideas",       href: "/party-night-outfit-ideas"          },
    { label: "Vacation Outfit Ideas",          href: "/vacation-outfit-ideas"             },
    { label: "Streetwear Outfit Ideas",        href: "/streetwear-outfit-ideas"           },
  ],

  relatedPages: [
    { label: "Date Night Outfit Ideas", href: "/date-night-outfit-ideas", desc: "Romantic looks for any evening out." },
    { label: "Office Outfit Ideas",     href: "/office-outfit-ideas",     desc: "Professional styles for the modern workplace." },
    { label: "Winter Outfit Ideas",     href: "/winter-outfit-ideas",     desc: "Cozy layered looks for the colder months." },
    { label: "Casual Outfit Ideas",     href: "/casual-outfit-ideas",     desc: "Effortless everyday looks that feel intentional." },
  ],
};

/* ── Metadata + page ──────────────────────────────────────────── */

export const metadata: Metadata = generateOutfitPageMetadata(config);

export default function OutfitIdeasPage() {
  return <OutfitIdeasTemplate config={config} />;
}
