"use client";

import { useState, useRef } from "react";
import Navbar from "@/components/sections/Navbar";
import Footer from "@/components/sections/Footer";
import StylistTool from "@/components/features/ai-stylist/StylistTool";
import { ArrowRight, Camera, Sparkles, ShoppingBag } from "lucide-react";
import BrandsStrip from "@/components/sections/BrandsStrip";

const U = "https://images.unsplash.com/photo-";

/* ── Data ─────────────────────────────────────────────────────── */

// Section 3 — Generated Outfit Examples
const GENERATED_EXAMPLES = [
  {
    label: "Oversized white tee",
    sub: "Black straight jeans · White sneakers",
    prompt: "Minimal streetwear outfit",
    img: `${U}1539109136881-3be0616acf4b?w=600&q=85&fit=crop&crop=top`,
    alt: "Minimal streetwear outfit — white tee and black jeans",
  },
  {
    label: "Grey cropped hoodie",
    sub: "Wide-leg cargo pants · Low-top sneakers",
    prompt: "Casual streetwear look",
    img: `${U}1490481651871-ab68de25d43d?w=600&q=85&fit=crop&crop=top`,
    alt: "Streetwear hoodie outfit generated by Slidez AI",
  },
  {
    label: "Fitted turtleneck",
    sub: "Wide-leg trousers · Leather ankle boots",
    prompt: "Smart minimal outfit",
    img: `${U}1524504388940-b1c1722653e1?w=600&q=85&fit=crop&crop=top`,
    alt: "Smart minimal outfit from Slidez AI Stylist",
  },
  {
    label: "Striped long-sleeve",
    sub: "Relaxed mom jeans · Canvas slip-ons",
    prompt: "Effortless casual outfit",
    img: `${U}1483985988355-763728e1935b?w=600&q=85&fit=crop&crop=top`,
    alt: "Effortless casual outfit — striped top and jeans",
  },
];

// Section 4 — Outfit Idea Library
const IDEA_LIBRARY = [
  {
    title: "Date Night Outfit Ideas",
    prompt:
      "Create a stylish date night outfit that feels elegant and confident. Include clothing pieces, color combinations, footwear, and accessories. The outfit should work for a dinner date or evening outing and feel modern and attractive.",
    img: `${U}1524504388940-b1c1722653e1?w=600&q=85&fit=crop&crop=top`,
    alt: "Date night outfit ideas",
  },
  {
    title: "Black Dress Outfit Ideas",
    prompt:
      "Style a black dress outfit with a complete look including shoes, accessories, and layering pieces. Suggest variations for casual, elegant, and evening occasions while keeping the outfit balanced and fashionable.",
    img: `${U}1515886657613-9f3515b0c78f?w=600&q=85&fit=crop&crop=top`,
    alt: "Black dress outfit ideas",
  },
  {
    title: "Casual Outfit Ideas",
    prompt:
      "Create a relaxed casual outfit that is comfortable but still stylish. Include clothing pieces, colors, footwear, and simple accessories suitable for everyday wear such as shopping, coffee runs, or hanging out with friends.",
    img: `${U}1539109136881-3be0616acf4b?w=600&q=85&fit=crop&crop=top`,
    alt: "Casual outfit ideas",
  },
  {
    title: "Party Outfit Ideas",
    prompt:
      "Create a bold party outfit suitable for a night out. Include statement pieces, trendy clothing combinations, footwear, and accessories that feel energetic, fashionable, and eye-catching.",
    img: `${U}1469334031218-e382a71b716b?w=600&q=85&fit=crop&crop=top`,
    alt: "Party outfit ideas",
  },
  {
    title: "Winter Outfit Ideas",
    prompt:
      "Create a stylish winter outfit that is warm but fashionable. Include layering pieces such as coats, sweaters, scarves, boots, and accessories while keeping the outfit modern and well coordinated.",
    img: `${U}1483985988355-763728e1935b?w=600&q=85&fit=crop&crop=top`,
    alt: "Winter outfit ideas",
  },
  {
    title: "Summer Outfit Ideas",
    prompt:
      "Create a light and stylish summer outfit suitable for warm weather. Include breathable clothing pieces, fresh color combinations, footwear, and accessories that feel comfortable, bright, and seasonal.",
    img: `${U}1507525428034-b723cf961d3e?w=600&q=85&fit=crop&crop=top`,
    alt: "Summer outfit ideas",
  },
  {
    title: "Office Outfit Ideas",
    prompt:
      "Create a professional office outfit that looks polished and modern. Include clothing pieces suitable for work environments such as blazers, shirts, trousers, or dresses along with appropriate footwear and accessories.",
    img: `${U}1490481651871-ab68de25d43d?w=600&q=85&fit=crop&crop=top`,
    alt: "Office outfit ideas",
  },
  {
    title: "Beach Outfit Ideas",
    prompt:
      "Create a relaxed beach outfit perfect for vacation or a beach day. Include lightweight clothing pieces, swimwear or layering options, sandals, sunglasses, and accessories that match a summer beach vibe.",
    img: `${U}1517841905240-472988babdf9?w=600&q=85&fit=crop&crop=top`,
    alt: "Beach outfit ideas",
  },
];

// Section 6 — How Slidez Helps
const HOW_IT_HELPS = [
  {
    icon: Camera,
    num: "01",
    title: "See the outfit on yourself",
    text: "Upload your photo and try outfits instantly.",
  },
  {
    icon: Sparkles,
    num: "02",
    title: "AI stylist suggestions",
    text: "Generate complete outfits from a single prompt.",
  },
  {
    icon: ShoppingBag,
    num: "03",
    title: "Try products before buying",
    text: "Experience fashion like a real store.",
  },
];

// Section 8 — FAQ
const FAQ = [
  {
    q: "What should I wear today?",
    a: "Describe the occasion, weather, or vibe in the prompt above — like 'casual Monday at the office' or 'brunch with friends.' Slidez AI Stylist generates a complete outfit in seconds.",
  },
  {
    q: "How does an AI stylist work?",
    a: "Type a short prompt describing your occasion or style preference. Slidez AI reads your description and assembles a full outfit — top, bottom, shoes, and accessories — matched to your request.",
  },
  {
    q: "Can I try outfits before buying?",
    a: "Yes. Slidez includes a virtual try-on feature that lets you see any outfit on your actual photo. Download the app on iOS or Android — free to use.",
  },
];

const POPULAR_IDEAS = [
  { label: "Black Jeans Outfit Ideas",       href: "/black-jeans-outfit-ideas"       },
  { label: "Summer Date Night Outfit Ideas", href: "/summer-date-night-outfit-ideas" },
  { label: "Casual Coffee Date Outfit",      href: "/casual-coffee-date-outfit"      },
  { label: "Winter Outfit Ideas",            href: "/winter-outfit-ideas"            },
  { label: "Office Outfit Ideas for Women",  href: "/office-outfit-ideas-for-women"  },
  { label: "Office Outfit Ideas for Men",    href: "/office-outfit-ideas-for-men"    },
  { label: "Concert Outfit Ideas",           href: "/concert-outfit-ideas"           },
  { label: "Party Night Outfit Ideas",       href: "/party-night-outfit-ideas"       },
  { label: "Vacation Outfit Ideas",          href: "/vacation-outfit-ideas"          },
  { label: "Streetwear Outfit Ideas",        href: "/streetwear-outfit-ideas"        },
];

/* ── Shared glow orb ──────────────────────────────────────────── */
function GlowOrb() {
  return (
    <div
      aria-hidden
      className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] h-[700px] rounded-full pointer-events-none"
      style={{
        background:
          "radial-gradient(ellipse at center, rgba(192,192,192,0.07) 0%, transparent 70%)",
      }}
    />
  );
}

/* ── Component ────────────────────────────────────────────────── */

export default function OutfitIdeasHubTemplate() {
  const [externalPrompt, setExternalPrompt]     = useState("");
  const [externalPromptKey, setExternalPromptKey] = useState(0);
  const heroRef = useRef<HTMLDivElement>(null);

  const fillPrompt = (prompt: string) => {
    setExternalPrompt(prompt);
    setExternalPromptKey((k) => k + 1);
    heroRef.current?.scrollIntoView({ behavior: "smooth", block: "center" });
  };

  return (
    <main className="overflow-hidden">
      <Navbar />

      {/* ─────────────────────────────────────────────────────────
          1. HERO — Tool First
      ───────────────────────────────────────────────────────── */}
      <section
        aria-label="AI outfit generator"
        className="relative min-h-screen flex flex-col items-center justify-center text-center px-6 pt-28 pb-24 bg-[#080808]"
      >
        <GlowOrb />

        <div className="relative z-10 w-full max-w-3xl mx-auto" ref={heroRef}>
          <h1 style={{ fontSize: '4rem', lineHeight: '1.05', letterSpacing: '-0.02em' }} className="font-bold mb-5">
            <span className="gradient-silver-text">Outfit Ideas for Any Occasion</span>
          </h1>

          <p className="text-lg text-white/45 max-w-md mx-auto mb-12 leading-relaxed">
            Describe your occasion or style.{" "}
            <span className="text-white/65">Slidez AI Stylist</span> creates outfits instantly.
          </p>

          {/* StylistTool includes the input + chips (sections 1 & 2) */}
          <StylistTool
            externalPrompt={externalPrompt}
            externalPromptKey={externalPromptKey}
          />
        </div>
      </section>

      {/* ─────────────────────────────────────────────────────────
          3. GENERATED OUTFIT EXAMPLES
      ───────────────────────────────────────────────────────── */}
      <section
        aria-label="Example AI-generated outfits"
        className="relative z-20 -mt-10 rounded-t-[2.5rem] overflow-hidden bg-white py-20 px-6"
      >
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-4">
            <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-black/30 mb-4">
              Style Inspirations
            </p>
            <h2 className="text-3xl md:text-4xl font-bold tracking-tight text-black">
              Outfit Ideas You Can Try
            </h2>
            <p className="mt-3 text-black/40 text-base max-w-sm mx-auto">
              Get inspired and create a look that fits your style.
            </p>
          </div>

          {/* Example prompt badge */}
          <div className="flex justify-center mt-7 mb-10">
            <span className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-black/10 bg-[#f5f5f5] text-sm text-black/55 font-medium">
              <Sparkles className="w-3.5 h-3.5 text-black/35" />
              Prompt: &ldquo;Minimal streetwear outfit&rdquo;
            </span>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {GENERATED_EXAMPLES.map(({ label, sub, prompt, img, alt }) => (
              <div
                key={label}
                className="group rounded-2xl border border-black/[0.07] bg-[#fafafa] overflow-hidden"
              >
                <div className="relative w-full aspect-[3/4] overflow-hidden bg-[#e8e8e8]">
                  <img
                    src={img}
                    alt={alt}
                    loading="lazy"
                    decoding="async"
                    className="absolute inset-0 w-full h-full object-cover group-hover:scale-[1.03] transition-transform duration-500"
                  />
                </div>
                <div className="p-4">
                  <p className="font-semibold text-black text-sm mb-0.5">{label}</p>
                  <p className="text-black/38 text-xs mb-3 leading-relaxed">{sub}</p>
                  <button
                    onClick={() => fillPrompt(prompt)}
                    className="text-[11px] font-semibold text-black/50 hover:text-black transition-colors duration-200 flex items-center gap-1"
                  >
                    Generate similar
                    <ArrowRight className="w-3 h-3" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─────────────────────────────────────────────────────────
          4. OUTFIT IDEA LIBRARY
      ───────────────────────────────────────────────────────── */}
      <section
        aria-label="Outfit idea library"
        className="relative z-30 -mt-10 rounded-t-[2.5rem] overflow-hidden bg-[#f5f5f5] py-20 px-6"
      >
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-12">
            <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-black/30 mb-4">
              Inspiration Library
            </p>
            <h2 className="text-3xl md:text-4xl font-bold tracking-tight text-black">
              Outfit Ideas for Every Occasion
            </h2>
            <p className="mt-3 text-black/40 text-base max-w-sm mx-auto">
              Tap any card to generate that look instantly.
            </p>
          </div>

          {/* Pinterest-style grid */}
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
            {IDEA_LIBRARY.map(({ title, prompt, img, alt }) => (
              <button
                key={title}
                onClick={() => fillPrompt(prompt)}
                className="group flex flex-col rounded-2xl border border-black/[0.07] bg-white overflow-hidden
                  hover:border-black/20 hover:shadow-md hover:-translate-y-1
                  transition-all duration-300 text-left cursor-pointer"
              >
                {/* Image */}
                <div className="relative w-full aspect-[3/4] overflow-hidden bg-[#e0e0e0] shrink-0">
                  <img
                    src={img}
                    alt={alt}
                    loading="lazy"
                    decoding="async"
                    className="absolute inset-0 w-full h-full object-cover group-hover:scale-[1.04] transition-transform duration-500"
                  />
                </div>

                {/* Text body */}
                <div className="p-4 flex flex-col gap-2.5 flex-1">
                  <p className="font-semibold text-black text-sm leading-snug">{title}</p>
                  <p className="text-black/45 text-xs leading-relaxed line-clamp-3">{prompt}</p>
                  <span className="inline-flex items-center gap-1.5 self-start mt-auto pt-1
                    px-3 py-1.5 rounded-full border border-black/20
                    text-[11px] font-semibold text-black/55
                    hover:bg-black/10 hover:border-black/50 hover:text-black
                    transition-all duration-200">
                    Generate similar style
                    <ArrowRight className="w-3 h-3" />
                  </span>
                </div>
              </button>
            ))}
          </div>
        {/* Brands strip inside inspiration section */}
        <div className="mt-14">
          <BrandsStrip
            title="Create outfits using brands like"
            subtitle=""
            variant="compact"
            theme="light"
          />
        </div>
        </div>
      </section>

      {/* ─────────────────────────────────────────────────────────
          5. SECOND TOOL SECTION
      ───────────────────────────────────────────────────────── */}
      <section
        aria-label="Create your outfit with AI"
        className="relative z-40 -mt-10 rounded-t-[2.5rem] overflow-hidden bg-[#080808] py-24 px-6"
      >
        <GlowOrb />

        <div className="relative z-10 w-full max-w-3xl mx-auto text-center">
          <p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-white/25 mb-6">
            AI Stylist
          </p>
          <h2 className="text-3xl md:text-4xl font-bold text-white tracking-tight leading-tight mb-4">
            Create Your Own Style With AI
          </h2>
          <p className="text-base text-white/40 max-w-sm mx-auto mb-10 leading-relaxed">
            Type anything — occasion, vibe, or a single item you want to build around.
          </p>

          {/* Independent tool instance — no external prompt injection */}
          <StylistTool />
        </div>
      </section>

      {/* ─────────────────────────────────────────────────────────
          6. HOW SLIDEZ HELPS
      ───────────────────────────────────────────────────────── */}
      <section
        aria-label="How Slidez helps"
        className="relative z-50 -mt-10 rounded-t-[2.5rem] overflow-hidden bg-white py-20 px-6"
      >
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-14">
            <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-black/30 mb-4">
              How It Works
            </p>
            <h2 className="text-3xl md:text-4xl font-bold tracking-tight text-black">
              How Slidez Helps
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
            {HOW_IT_HELPS.map(({ icon: Icon, num, title, text }) => (
              <div
                key={title}
                className="relative p-8 rounded-2xl border border-black/[0.07] bg-[#fafafa] overflow-hidden"
              >
                <span className="absolute top-5 right-6 text-[5rem] font-bold leading-none text-black/[0.04] select-none pointer-events-none">
                  {num}
                </span>
                <div className="relative z-10">
                  <div className="w-12 h-12 rounded-2xl bg-black flex items-center justify-center mb-6">
                    <Icon className="w-5 h-5 text-white" />
                  </div>
                  <p className="font-semibold text-black text-base mb-2 leading-snug">{title}</p>
                  <p className="text-black/40 text-sm leading-relaxed">{text}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─────────────────────────────────────────────────────────
          7. TRY WITH SLIDEZ CTA
      ───────────────────────────────────────────────────────── */}
      <section
        aria-label="Try with Slidez"
        className="relative z-[55] -mt-10 rounded-t-[2.5rem] overflow-hidden bg-[#080808] py-24 px-6"
      >
        <GlowOrb />

        <div className="relative z-10 max-w-xl mx-auto text-center">
          <p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-white/25 mb-6">
            Virtual Try-On
          </p>
          <h2 className="text-4xl md:text-5xl font-bold text-white tracking-tight leading-tight mb-8">
            Open Slidez AI Stylist
          </h2>

          <ul className="flex flex-col items-center gap-3.5 mb-10 text-center">
            {[
              "Upload your photo",
              "Generate outfits with AI Stylist",
              "Try clothes before buying",
            ].map((point) => (
              <li key={point} className="flex items-center justify-center gap-3 text-white/50 text-base">
                <span className="w-1.5 h-1.5 rounded-full bg-[#c0c0c0] shrink-0" />
                {point}
              </li>
            ))}
          </ul>

          <a
            href="https://linkly.link/2FWYm"
            className="inline-flex items-center gap-2.5 px-8 py-4 bg-white text-black text-sm font-semibold rounded-full
              shadow-[0_2px_16px_rgba(255,255,255,0.28),0_1px_4px_rgba(0,0,0,0.25),inset_0_1px_0_rgba(255,255,255,0.9)]
              hover:shadow-[0_4px_28px_rgba(255,255,255,0.45)] hover:scale-[1.05] hover:-translate-y-px
              active:scale-[0.97] transition-all duration-200"
          >
            Open Slidez AI Stylist
            <ArrowRight className="w-4 h-4" />
          </a>
        </div>
      </section>

      {/* ─────────────────────────────────────────────────────────
          8. SHORT FAQ
      ───────────────────────────────────────────────────────── */}
      <section
        aria-label="AI outfit generator FAQ"
        className="relative z-[60] -mt-10 rounded-t-[2.5rem] overflow-hidden bg-[#f5f5f5] py-20 px-6"
      >
        <div className="max-w-2xl mx-auto">
          <div className="text-center mb-12">
            <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-black/30 mb-4">
              Questions
            </p>
            <h2 className="text-3xl md:text-4xl font-bold tracking-tight text-black">
              Frequently Asked
            </h2>
          </div>

          <div>
            {FAQ.map(({ q, a }, i) => (
              <details key={i} className="group border-b border-black/[0.08] last:border-b-0">
                <summary className="flex items-center justify-between gap-4 py-5 list-none cursor-pointer [&::-webkit-details-marker]:hidden">
                  <span className="text-base md:text-lg font-semibold text-black group-hover:text-black/65 transition-colors duration-200 text-left">
                    {q}
                  </span>
                  <span className="shrink-0 w-7 h-7 rounded-full border border-black/10 flex items-center justify-center text-black/40 group-hover:border-black/25 group-hover:text-black/60 transition-all duration-200 relative">
                    <span className="block w-3 h-px bg-current" />
                    <span className="block w-px h-3 bg-current absolute group-open:opacity-0 transition-opacity duration-200" />
                  </span>
                </summary>
                <p className="pb-5 text-black/55 text-base leading-relaxed">{a}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

      {/* ── Popular Outfit Ideas (SEO) ───────────────────────────── */}
      <section
        aria-label="Popular outfit ideas"
        className="relative z-[65] -mt-10 rounded-t-[2.5rem] overflow-hidden bg-white py-20 px-6"
      >
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-10">
            <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-black/30 mb-4">
              Browse by Style
            </p>
            <h2 className="text-3xl font-bold tracking-tight text-black">
              Popular Outfit Ideas
            </h2>
          </div>

          <ul className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">
            {POPULAR_IDEAS.map(({ label, href }) => (
              <li key={href}>
                <a
                  href={href}
                  className="block px-4 py-3.5 rounded-xl border border-black/[0.07] bg-[#fafafa] text-center
                    text-sm font-medium text-black/55
                    hover:border-black/[0.18] hover:bg-white hover:text-black hover:shadow-sm
                    transition-all duration-200"
                >
                  {label}
                </a>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* ── Footer ──────────────────────────────────────────────── */}
      <div className="relative z-[70] -mt-10 rounded-t-[2.5rem] overflow-hidden">
        <Footer />
      </div>
    </main>
  );
}
